### ISSUE TITLE
Add Show Debug Log Feature and more flexible UI

### ISSUE THREAD

**Issue by wolewd** [omid3098/Terminal#12]
i think its good addition to show my Debug.Log from my script to make sure its work perfectly and maybe you can set the UI so it more customizable.

**Comment by omid3098** [comment]
Showing Debug.Log() from scripts makes this a [LogViewer](https://github.com/omid3098/OpenLogView) which is not the main purpose of this repo.
However you can return any string from your method and it will be shown in terminal:
```csharp
  [TerminalCommand("method", "executes my custom mathod")]
    public string MyMethod()
    {
      string logMessage = "method executed!";
      Debug.Log(logMessage);
      return logMessage;
    }
```

**Comment by omid3098** [comment]
And what Ui customization do you want?

**Comment by wolewd** [comment]
hello thanks for the reply
the UI is current based on text script, for someone like me who not really good in coding can be confusing
maybe you can change it like this

```csharp
using UnityEngine;
using.UnityEngine.UI;

public class Example : MonoBehaviour
{
   // this is UI customization
   public InputField inputCommand; 
   public ScrollRect inputLog;
   public Text inputText;

   void Update()
   {
      //do something
   }
```

**Comment by wolewd** [comment]
thanks for your reply!
your explanations solve my problem

**Comment by omid3098** [comment]
Using UGUI for showing and using command requires additional gameobjects, it will cause additional considerations to load/unload them and a little more impact on performance. So unfortunately this will not happen.
