### ISSUE TITLE
TerminalMethods really slow on big projects

### ISSUE THREAD

**Issue by bendangelo** [omid3098/Terminal#5]
I have a big project with lots of classes and the `TerminalMethods` class takes forever gathering all the attributes.

I made a work around by only getting attributes from monobehaviours in scene. This is much quicker and works for my use case. Let me know if you want a PR.

**Comment by omid3098** [comment]
It would be very nice of you to send a PR.
It seems logical to check only monobehavoiur attributes. But why just only the ones in the scene?

**Comment by bendangelo** [comment]
I meant all the game objects. I can open one in a bit.

**Comment by bendangelo** [comment]
https://github.com/omid3098/OpenTerminal/pull/6
