### ISSUE TITLE
TargetParameterCountException

### ISSUE THREAD

**Issue by vncastanheira** [omid3098/Terminal#8]
Hello! Great terminal extension!

I found something that was probably a bug. 
If you type `rotate-cube` on the Sample scene, Unity throws a `TargetParameterCountException`. It would probably be best to inform the user about the invalid command, rather than halting the game.

It's on line 165 in `Terminal.cs`.

Let me know what you think!

**Comment by omid3098** [comment]
Hello and thank you for your feedback.
what you mentioned is right. and I've stop invoking methods with invalid arguments and also added a log telling user what is wrong there.
please update repository and check if its fixed for you.
