### ISSUE TITLE
Property done is deprecated, use status instead

### ISSUE THREAD

**Issue by bendangelo** [omid3098/Terminal#9]
```
Assets/Plugins/OpenTerminal/Scripts/TerminalInputHandler.cs(59,46): warning CS0618: `UnityEngine.TouchScreenKeyboard.done' is obsolete: `Property done is deprecated, use status instead'
```

Using 2018.2.18f1

**Comment by mohakdev** [comment]
Replace `if (terminal.touchScreenKeyboard.done)` with `if (terminal.touchScreenKeyboard.status == TouchScreenKeyboard.Status.Done)` in `TerminalInputHandler.cs` to fix the error

**Comment by omid3098** [comment]
this is already fixed in the latest commit.
